spring:
  data:
    cassandra:
      contact-points: cassandra-container
      port: 9042
      local-datacenter: datacenter1
      keyspace-name: products_keyspace
      schema-action: create-if-not-exists
  main:
    allow-bean-definition-overriding: true
server:
  port: 8081
